### ISSUE TITLE
Declare license on repositories: MIT

### ISSUE THREAD

**Issue by GeorgLink** [badging/meta#19]
As a CHAOSS project, these repositories need to be licensed under MIT. (see [Project Charter 8.3.2](https://chaoss.community/about/charter/#user-content-8-intellectual-property-policy))

This issue is asking to add a LICENSE file in each repo with the MIT license text.

Example: https://github.com/chaoss/wg-evolution/blob/master/LICENSE

**Comment by Nebrethar** [comment]
Thank you Georg for proposing this. I will declare the licenses after the D&I meeting.

**Comment by GeorgLink** [comment]
Thank you :)

**Comment by Nebrethar** [comment]
I didn't put it in my calendar and I failed! I have updated my comment. My apologies

**Comment by Nebrethar** [comment]
Done! Thanks Georg :)
