### ISSUE TITLE
Documentation: Creating a centralized documentation repository.

### ISSUE THREAD

**Issue by SMotaal** [badging/meta#28]
> **Important Note**: This issue is being closed for now and will be revisited after closing #29.

This issue tracks the process of moving all non-contributor-facing documentation into https://github.com/badging/documentation.

**Comment by tharun143** [comment]
@SMotaal Even though this is assigned to you. If you need any help mention me. I am happy to help you.

**Comment by germonprez** [comment]
I think this is an excellent idea!

**Comment by SMotaal** [comment]
@tharun143  — we have an after hour meeting after the D&I meeting today, do you want to join?

> Can you email me so I could add you to the calendar even? I tried looking you up in the unofficial slack, and I can send you an invite too if you want :)

---

🚀 I sent you an invite to the badging org

**Comment by tharun143** [comment]
@SMotaal Oh, I missed today's meeting. Ah...!! 
tharunravuri2000@gmail.com this is my mail id. Try adding me for the next meetings 
Sorry I missed the meeting.

**Comment by xiaoya-yaya** [comment]
I think I get lost in the badging office hours...

`Badging hour after D&I meeting`
Do we have after hour meetings after the D&I meeting every week at the link https://zoom.us/j/885031449?pwd=ak1mdnY1cWNwbDBndFMzSy9oa1FFUT09 ? If so, I missed it again！💔

`Badging weekly minutes on Sunday`
From the [badging weekly minutes](https://docs.google.com/document/d/1WrY4PjOrC_Fp6aiWFjfRRZuujlolSraUlTAJHPfbw9I/edit#heading=h.wztaalmdd7vm) , I can see the schedule of **The Weekly Minutes** is every Sunday, but I failed to find out the meeting hour and place in slack or elsewhere.

`Season of Docs Office Hours`
And there is Season of Docs Office Hour today, [link.](https://calendar.google.com/event?action=TEMPLATE&tmeid=NDZnODRqczh2MDlrN2tzMW1tbWk5bm9qNzZfMjAyMDA2MTFUMTQwMDAwWiBjazQxcjVhZGNsMGxkMjBqazU0bDQ3NDFoZ0Bn&tmsrc=ck41r5adcl0ld20jk54l4741hg%40group.calendar.google.com&scp=ALL) I will make it!

**Comment by SMotaal** [comment]
> **Important Note**: Closing for now and will revisit after closing #29

**Comment by SMotaal** [comment]
sorry for the mess with redundant issues

/cc @xiaoya-Esther @bistaastha
